name: Build Check

# Esto permite que n8n dispare el proceso manualmente
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # O la versión que uses
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar el Build
        run: npm run build